<h1>Deu tudo certo por aqui!</h1>
<br>
<h3>Nome:</h3>
<p>{{$nome}}</p>
<br>
<h3>Email:</h3>
<p>{{$email}}</p>
<br>
<h3>Telefone:</h3>
<p>{{$telefone}}</p>
<br>
<h3>cargo:</h3>
<p>{{$cargo}}</p>
<br>
<h3>Escolaridade:</h3>
<p>{{$escolaridade}}</p>
<br>
@if(isset($observacoes))
<h3>Observações:</h3>
<p>{{$observacoes}}</p>
<br>
@endif